### PR TITLE
Feature/logstash 5

### PR DESCRIPTION
**Pull request by savelandr**
I am updating this to be able to be used with Logstash 5.x.  I built the gem and installed it (via the file) into Logstash 5.6.2 to verify it installed.  I also tested that it output stats to a locally running statsd as an output plugin.

I don't believe any new tests are needed as the behaviors should be identical.  However, if there's anything I'm missing, please let me know.

I upped the gem version from `2.0.0` to `5.0.0` to reflect the Logstash version compatibility, but maybe that's not appropriate for the gem.

### CODE REVIEW

**Comment by tdooner** [comment]
Hey @z3usy, I'm happy to take over maintenance of this repo if you'd like to transfer it to me. This patch looks good to me (thank goodness we can get that hack out of there). Also, you might want to check the Brigade chef configs to make sure that there is a specific version of the plugin pinned so that it doesn't upgrade automatically as soon as this is merged.

Thanks for the contribution @savelandr!

**Comment by johndotpub** [comment]
@tdooner I've added you as a collaborator! Glad to hear you're interested in maintaining the project!

@Chillmatik can you confirm the version pinning one way or another before this get's merged?

**Comment by 0xOI** [comment]
@z3usy roger that, Brigade's chef configs are currently pinned to **v1.3.0** so no worries on applying updates.

@tdooner sweeeeet !)

**Comment by tdooner** [comment]
Great, gonna merge this then. Thanks all for coming together to make this plugin work well.

**Pull request merged**
